### ISSUE TITLE
Extra single quote for "Relayhost's role" in metadata.rb breaks Berkshelf upload.

### ISSUE THREAD

**Issue by nkadelgarcia-consultant** [opscode-cookbooks/postfix#93] opened 2014-10-20 18:31 UTC
When using Berkshelf 0.3.0, and Berkshelf 0.2.0 on CentOS 6, the resulting metadata.json is broken. Uploads that rely purely on 'metadata.rb' seem to work well, and the issue generating metadata.json seems to be the embedded single quote in the phrase "Relayhost's role".

Even if the single quote isn't the issue, embedding quotes inside quoted text is asking for trouble in the future. This one is also not syntactically necessary.

**Comment by thommay** [comment] 2015-06-23 09:49
I can't reproduce this - the generated json is perfectly valid and single quotes in json strings are fine. Closing.

**Closed by thommay** 2015-06-23 09:49 UTC
